# Reprising the content of __init__, just to be safe

class DictionaryLoadingError(Exception): ...

class Speller:
	def __init__(self, base_path: str, lang_code: str) -> None: ...
	def spell(self, word: str) -> bool: ...
	def suggest(self, word: str) -> list[str]: ...
	def analyse(self, word: str) -> list[str]: ...
	def stem(self, word: str) -> list[str]: ...
	def orthographic_forms(self, word: str) -> list[str]: ...
